# Generated by Django 3.1.3 on 2021-05-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypersonaldata',
            name='Languages',
            field=models.CharField(max_length=80),
        ),
    ]
