# Generated by Django 3.1.3 on 2021-05-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_blog_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='technologies',
            field=models.CharField(default='', max_length=20),
        ),
    ]
