# Generated by Django 3.1.3 on 2021-05-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_portfolio_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='preview',
            field=models.CharField(default='', max_length=30),
        ),
    ]
