# Generated by Django 3.1.3 on 2021-05-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210515_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='client',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image2',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='preview',
            field=models.CharField(max_length=30),
        ),
    ]
